### PR TITLE
Fix SVG alignment and click box

### LINKED ISSUE #92: Fix decoration appearing after GitLens Current Line Blame
This happens if another plugin tries to put something at the end of the line, eg GitLens's [Current Line Blame](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens#current-line-blame-).  Notice how the final gray dot is all the way off to the right:

image

This could probably be fixed by using the svg `before` instead of `after`

### LINKED ISSUE #110: SVG hat obstructs click target area
If the user clicks on a letter with a hat over it, the cursor will end up to the right of the letter, unless the user clicks significantly to the left of the letter

### PR DESCRIPTION
**Pull request by pokey**
I adjusted the measurements to fix the math bug for my setup, but unfortunately different users will be affected proportional to the square of the ratio of their character width to the ceiling of the width, so they'll unfortunately need to do their own tweaking if they've adjusted their defaults

image

Note that the hats have moved up very slightly, but it is minor, and we will tweak these heights in #269 anyway

Fixes #110
Fixes #92 

And possibly #78

### CODE REVIEW

File: src/core/Decorations.ts [hunk 1]
```diff
@@ -150,24 +147,24 @@ export default class Decorations {
...
                 svg,
                 colorSetting.dark
               ),
             },
           },
-          after: {
-            margin: `-${svgHeightPx}px 0 0 -${spanWidthPx}px`,
-            width: `${spanWidthPx}px`,
+          before: {
+            margin: `-${svgHeightPx}px -${svgWidthPx}px 0 0`,
```
Comment (pokey) [inline src/core/Decorations.ts:166]: No need to play games with span width anymore because we now align to the left side of the char

File: src/core/Decorations.ts [hunk 2]
```diff
@@ -150,24 +147,24 @@ export default class Decorations {
...
+            width: `${svgWidthPx}px`,
```
Comment (pokey) [inline src/core/Decorations.ts:167]: No need to play games with span width anymore because we now align to the left side of the char

File: src/core/Decorations.ts [hunk 3]
```diff
@@ -261,25 +258,24 @@ export default class Decorations {
...
-    const svgWidthPx = Math.ceil(fontMeasurements.characterWidth);
-    const svgHeightPx =
-      fontMeasurements.characterHeight + hatHeightPx + hatVerticalOffset;
+    const svgWidthPx = Math.ceil(characterWidth);
+    const svgHeightPx = characterHeight + hatHeightPx + hatVerticalOffset;
 
     const newViewBoxWidth =
-      ((originalViewBoxWidth / hatWidthToCharacterWidthRatio) *
-        fontMeasurements.characterWidth) /
-      svgWidthPx;
```
Comment (pokey) [inline src/core/Decorations.ts:280]: This was the dumb mistake.  We need to adjust from char width to svg width, not the other way around 😅

File: src/core/Decorations.ts [hunk 4]
```diff
@@ -261,25 +258,24 @@ export default class Decorations {
...
+      ((originalViewBoxWidth / hatWidthToCharacterWidthRatio) * svgWidthPx) /
+      characterWidth;
     const newViewBoxHeight = (newViewBoxWidth * svgHeightPx) / svgWidthPx;
-    const newViewBoxX = -(newViewBoxWidth - originalViewBoxWidth) / 2;
+    const newViewBoxX =
+      (-(characterWidth - hatWidthPx) * (newViewBoxWidth / svgWidthPx)) / 2;
```
Comment (pokey) [inline src/core/Decorations.ts:278]: Since we're left-aligned, we basically need to shift right by `(characterWidth - hatWidthPx) / 2`, translated to svg view box space (`newViewBoxWidth / svgWidthPx`)

**Review by AndreasArvidsson — APPROVED** [review]
